### ISSUE TITLE
No Garbage collection ?  

### ISSUE THREAD

**Issue by zle000** [GaijinEntertainment/daScript#1064]
**How does garbage collection work in Dascript? Is it necessary to promptly delete newly created objects?**
For example，in one context ， 
```
class X
    ...
    ...

for i in range(1,10000)
    let x = new X()
```
The object x won't be destroyed. unless I call 
```
unsafe
    delete x
```
Is it like this?

**Comment by borisbat** [comment]
can be called externally by integration, can be called explicitly as "heap_collect". im going to write a blog post about it. the idea is that integration calls it, and application keeps those calls rare and manageable by manually deleting objects with obvious lifetime. additionally at some point compiler will automatically replace some of the let via let inscope - where appropriate.

**Comment by zle000** [comment]
> can be called externally by integration, can be called explicitly as "heap_collect". im going to write a blog post about it. the idea is that integration calls it, and application keeps those calls rare and manageable by manually deleting objects with obvious lifetime. additionally at some point compiler will automatically replace some of the let via let inscope - where appropriate.

Thank you very much！ I look forward to your blog ):

**Comment by borisbat** [comment]
https://borisbat.github.io/dascf-blog/2024/04/16/gc-in-the-wild/
