### ISSUE TITLE
where is libclang

### ISSUE THREAD

**Issue by gh16980973** [GaijinEntertainment/daScript#1070]
https://github.com/GaijinEntertainment/daScript/blob/b21c973337697c82267c6e4f9af3481dd6c5bb79/modules/dasClangBind/CMakeLists.txt#L2

**Comment by borisbat** [comment]
Typically https://releases.llvm.org/download.html

**Comment by otakubeam** [comment]
We are on the 16.0.6 version.
There is also https://github.com/awakecoding/llvm-prebuilt/releases/tag/v2023.3.0
iirc you might need headers from there
