### ISSUE TITLE
30304: function not found 

### ISSUE THREAD

**Issue by zle000** [GaijinEntertainment/daScript#1075]
```
def override aaF() : void
                 ^^^
24:17 - 24:19
30304: function not found _::BaseGameObject`aaF

```

about "_::BaseGameObject`aaF", what is the ```_``` meaning? it mean not find module of it,or it is a built-in module ?

I don't know how make this error,I just adjust my das file dir....

**Comment by zle000** [comment]
[Error.zip](https://github.com/GaijinEntertainment/daScript/files/15129572/Error.zip)
This is the code,I make the error...

**Comment by borisbat** [comment]
require BaseClsInDir public as oppose to require BaseClsInDir in ClsInDir.das
what happens is that default visibility on require is private, and main does not see BaseClsInDir
i'll try to do something with the error message, to make this more robust

also, i've noticed u'r missing 'module' declarations. while not the end of the world, it would help to add them - as well as specify visibility explicitly.

**Comment by zle000** [comment]
> require BaseClsInDir public as oppose to require BaseClsInDir in ClsInDir.das what happens is that default visibility on require is private, and main does not see BaseClsInDir i'll try to do something with the error message, to make this more robust
> 
> also, i've noticed u'r missing 'module' declarations. while not the end of the world, it would help to add them - as well as specify visibility explicitly.

Thank you for your help, I missed the 'public' keyword; I didn't read the documentation carefully :)

**Comment by borisbat** [comment]
D:\Work\daScript\examples\error\ADir/BaseClsInDir.das:9:17:
    def override Func() : void
                 ^^^^
9:17 - 9:20
30304: function not found _::BaseClsInDir`Func
        BaseClsInDir::BaseClsInDir`Func ( self : BaseClsInDir::BaseClsInDir ) : void at D:\Work\daScript\examples\error\ADir/BaseClsInDir.das:9:17
                module BaseClsInDir is not visible directly from the current module

with https://github.com/GaijinEntertainment/daScript/pull/1081
