### ISSUE TITLE
How to correctly require the parent module or somewhere ？

### ISSUE THREAD

**Issue by zle000** [GaijinEntertainment/daScript#1080]
```
├── src
│   ├── dirA
│   │   └── moduleA.das
│   └── dirB
│       ├── moduleB.das
│       └── moduleC.das
```

```
//moduleB.das
require ../dirA/moduleA
```
It show this isn't right..., the dascript replaced '../' with '///'.  （：

**Comment by zle000** [comment]
I find way:
write xx.das_project and set the it to vscode like this: ${workspaceFolder}/FileSearch.das_project,in this das_project  file, write file search logic , by the way,also search c++ custum module api tip code, I put it in somewhere, the tip code just for code complete with empty function body 
I don't know if there are any better ways. ):

**Comment by borisbat** [comment]
Project is typically the best way to make any custom require scheme to work.
