### ISSUE TITLE
How to export a array<c++ struct> to das ?

### ISSUE THREAD

**Issue by zle000** [GaijinEntertainment/daScript#1091]
In the source code examples of tutorial03,we have a struct Color
```
struct Color {
    uint8_t r, g, b, a;
    float luminance() const { return 0.2126f*r + 0.7152f*g + 0.0722f*b; }
};
```
Now , I want export a Array<Color> to das, How make it  ?  Is there a example for reference?  ):
```
// like this,call from das
Array<Color> GetArray();
```

**Comment by borisbat** [comment]
return TArray<Color> from your function. Array needs to be constructed manually on C++ side, with data allocated on context->heap. Bind with SimNode_ExtFuncCallAndCopyOrMove.
Alternatively pass temporary array to the block, like in builtin_map_file in fio.

**Comment by zle000** [comment]
> return TArray from your function. Array needs to be constructed manually on C++ side, with data allocated on context->heap. Bind with SimNode_ExtFuncCallAndCopyOrMove. Alternatively pass temporary array to the block, like in builtin_map_file in fio.

Thank you for your help ):
I will code the function like  this 
```
Array<Color> GetArray() {
    static std::vector<Color> temp_data;
    ...
    set TArray's data use temp_data.data()
    ....
    return TArray
}
```
should be work, for void allocate memory  ~_~

**Comment by borisbat** [comment]
the code above likely won't work. temp_data will be destroyed once out of scope of GetArray(). TArray.data = code->heap->allocate ( temp_data.size() * sizeof(Color) ); memcpy... all that.
