### ISSUE TITLE
How to list exported symbols from modules

### ISSUE THREAD

**Issue by moleium** [GaijinEntertainment/daScript#1099]
I'm working on a project that involves dynamically using functions from different modules.
Is there a built-in way to get a list of all functions and variables exported by a module (reflection?)

**Comment by borisbat** [comment]
module_for_each_function in rtti, module_for_each_global as well. that is if u really want to go via RTTI. a lot more is available wia 'ast' module and macros.

**Comment by moleium** [comment]
Thank you.
