### ISSUE TITLE
tutorial_07a crash because of das_structure_make()

### ISSUE THREAD

**Issue by EthanCS** [GaijinEntertainment/daScript#1144]
`das_modulegroup_make()` create ModuleLibrary but there is no C api to add module, so ModuleLibrary's `thisModule` is always  `nullptr`, and `das_structure_make()` rely on `getThisModule()` , so crash.

Maybe consider add an interface like this:
```
void das_modulegroup_add_module(das_module_group* lib, das_module* mod) {
    ((ModuleGroup*)lib)->addModule((Module*)mod);
}
```
And modify tutorial_07a to this:
```
    das_module * mod = das_module_create ("tutorial_07a");
    das_module_group * lib = das_modulegroup_make();
    das_modulegroup_add_module(lib, mod);
```

**Comment by borisbat** [comment]
https://github.com/GaijinEntertainment/daScript/pull/1150

thank you
