### ISSUE TITLE
C++ destructors and/or shared pointers/reference counting?

### ISSUE THREAD

**Issue by ihm-ts** [GaijinEntertainment/daScript#121]
I've been trying to get daScript to handle shared pointers and destructors with C++ types without success, and I'm not sure if the documentation covers whether this is possible. The section on finalizers and classes does mention that I can't really rely on them being called, but I'm not sure if that also applies to C++ types or if I'm just doing something wrong. The root of the issue is that my C++ destructors are ignored, and I can't get daScript to call them with any combination of annotation overrides, or detect it with any simulate* events. Similarly, anything that wraps types with shared pointers cause them to leak if I pass them to a script.

Simplified example of what I'm trying to do, `gen` and `map` being exposed C++ types and the functions that create them similar to the one in your `tutorial03.cpp`:

```
[export]
def left_click()
   // wraps a type from a library that use shared pointers internally, and they leak if I do this
   var gen = create_noise_generator(some_settings);
   
   for x in range(some_large_number)
      for y in range(some_large_number)
          // may handle a very large array, so need to be deallocated between each iteration
          var map = create_noise_map(gen,x,y)
```

For things like `gen`, I can just let the host manage references and deallocate everything after the script is done, but for things like `map` the application may run out of memory long before that. Do I need to provide manual deallocator functions for situations like that?

**Comment by AntonYudintsev** [comment]
Yes, in such situations (i.e. allocation within loop) you have to deallocate manually.
I am not entirely sure what create_noise_map is returning, if it is some C++ handled type (say map), than probably you can bind clear(map), which frees heap (i.e. .clear() + .shrink_to_fit()).
If it is some pointer type than you can provide delete node and call:
[unsafe]
  delete map

**Comment by AntonYudintsev** [comment]
BTW, safest way to do that would be binding or writing function that accepts block as parameter, calls it, and just frees the map after 
i.e.
create_noise_map(gen,x,y) <| $ (var map: SomeMap)
   ...work with map...

examples are fio, json, etc
for example:
require fio
...
  fopen("somefile.txt", "r") <| $ ( f )
    we work here with opened file, and don't bother closing it, as it will be done by fopen function

where  fopen is provided in fio.das as:

[generic]
def fopen(name:string;mode:string;blk:block<(f:file):void>)
    let f = fopen(name,mode)
    invoke(blk,f)
    if f!=null
        fclose(f)

**Comment by ihm-ts** [comment]
Thank you for the quick and thorough response! I can easily fix that with our current setup, just wasn't sure if I missed some refcounting feature and would end up having to remove my solution later. This resolves my issue, but you may wish to add a line to the documentation mentioning C++ destructors and refcounting in general.
