### ISSUE TITLE
Can there be an explination in the doc on how to install and execute scripts.

### ISSUE THREAD

**Issue by Retkid** [GaijinEntertainment/daScript#122]
As it stands, on arch linux, after building, I am way too in the weeds to understand how to get it to work and, trying to figure it out isn't justifying the time. I don't think it would be very hard to do some bash scripting; hell, if you explain it to me I'll write the bash script that compiles and install the scripts.

**Comment by AntonYudintsev** [comment]
There is some bash script already
generate_gcc_linux.sh 
it's not good enough?

**Comment by Retkid** [comment]
It generates the scripts to execute, but how the hell do I run a .das when there is no explanation of it works? it doesn't go in /usr/bin or wherever your ${PATH} is. To execute a python script, you type python x.py/pyx, for das you do ??? do you do daScript xyz.das? no, that doesn't work. Do you convert it to C then run it with daScript? and so on.

**Comment by pkit** [comment]
If you peek inside `CMakeLists.txt` you'll find all the executables it compiles (look for `add_executable`)
It looks like `./daScript foo.das` is what you need to run stuff.

**Comment by uniqss** [comment]
Reading or just try building and executing the examples/tutorial code is very helpful, and you can change the das from the tutorials to have some fun.

**Comment by lvdpower** [comment]
Could you please provide the information how to use dascript with 3D (opengl or BGFX). I was trying to enable in cmake option BGFX, but with this I am getting error - [ 27%] Built target daScript
[ 27%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/opengl_boost.das -> /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
[ 27%] Built target dasImguiOpenGL_AOT_opengl_boost.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_demo.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_demo.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_opengl2.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_opengl2.das_aot
make[2]: *** No rule to make target `../modules/dasImgui/imgui/imgui_boost.das', needed by `../modules/dasImgui/imgui/_aot_generated/dasImguiOpenGL_AOT_imgui_boost.das.cpp'.  Stop.
make[1]: *** [CMakeFiles/dasImguiOpenGL_AOT_imgui_boost.das_aot.dir/all] Error 2
make: *** [all] Error 2     .   I have installed BGFX library in system via  build this https://github.com/bkaradzic/bgfx.cmake and sudo make install , but this did not help.  Thank you and for any who can help. timur123@gmail.com   Timur

**Comment by Retkid** [comment]
Keep in mind i wrote this a long time ago, I could probably get it working now.

This kind of stuff should be in the docs though, at some point.
