### ISSUE TITLE
AOT BUG

### ISSUE THREAD

**Issue by MaxwellGengYF** [GaijinEntertainment/daScript#1230]
In this simple example:
`
[export]
def main(){
    let test_block <- ${
        print("hello world\n");
    };
    invoke(test_block);
}
`
We have:
`
auto __test_block_rename_at_20_0_ConstRef; das_zero(__test_block_rename_at_20_0_ConstRef); das_move(__test_block_rename_at_20_0_ConstRef, (das_make_block<void>(__context__,0,0,&__func_info__5ba3c225af0ca06e,__test_block_rename_at_20_0_TempFunctor)));
`
and compile error:
error: declaration of variable '__test_block_rename_at_20_0_ConstRef' with deduced type 'auto' requires an initializer

**Comment by borisbat** [comment]
https://github.com/GaijinEntertainment/daScript/pull/1231

local block variables were added fairly late, hence the lack of coverage \ use tests
