### ISSUE TITLE
How to do garbage collection?

### ISSUE THREAD

**Issue by ihm-ts** [GaijinEntertainment/daScript#124]
Hi again!

We've been looking at trying out the GC features, but I can't seem to get it right and the documentation doesn't say very much about it.

**(fix for strings below, still investigating non-strings)**

## What I'm currently doing:

We use this code to execute functions:
```c++
auto fun = ctx->findFunction("left_click");
ctx->eval(fun, nullptr);
ctx->stringHeap->mark();
ctx->stringHeap->sweep();
```

The extern function we have to allocate strings on your heap:
```c++
char const* get_string_param(char const* path, das::Context * ctx)
{
  auto str = get_json_unsafe<std::string>(path);
  return ctx->stringHeap->allocateString(str.c_str(),str.size());
}
```

The daScript code we use to call it (temporarily worstDefault so it won't be optimized away):
```
[export]
def left_click()
    get_string_param("some key")
```

But this is leaking memory, are we doing something wrong? I noticed there was a slightly more involved function with `Context#collectStringHeap`, but that one doesn't seem to work either.

**Comment by borisbat** [comment]
most likely context is using 0GC, and not persistent heap
i.e u need
options persistent_heap = true
options persistent_string_heap = true

**Comment by borisbat** [comment]
on the similar note - its a lot faster to use 0GC and reset context, than to use persistent GC and collect
also likely mark\sweep should not be called every time

lastly, external function does not have to allocate string on our heap. it can return temporary value, or, better yet invoke a block, where temporary value is a parameter. string peek is an example of such function

**Comment by ihm-ts** [comment]
Thanks! 

By using this at the top of my script: 
```
options persistent_heap = true
options persistent_string_heap = true
```

and by invoking the gc via  `ctx->collectStringHeap(nullptr)` instead of mark/sweep it seems I am able to correctly keep track of string references in the global scope.

### Remaining issues
- I couldn't find a similar function that worked for the normal heap. Can I do this with non-strings? It looks like mark always returns false for other allocators.

- Can I force these options (`persistent_heap` etc) for a program from the C++ side? I'm guessing it's the `program->options` vector, do I just fill that up with values somehow?

### (second comment)
I'm just cleaning it every time to debug it for now, I'll probably use `ctx->stringHeap->bytesAllocated` along with some counter for when to invoke it in production, but GC cost isn't very important for our tool. We're using daScript in a map editor, so we would like to allow scripters to store large strings, images and noisemaps in the global scope between events:

```
var big_image = empty_image();

[export]
def left_click()
    if(!is_loaded(big_image))
        load_image(big_image,"some/image/path.png");
    ....
```

**Comment by ihm-ts** [comment]
Looks like I can do this to set default options from C++:

```c++

auto program = compileDaScript(....);

// do this right after compiling the program, before simulating.
if (!program->options.find("persistent_heap",das::Type::tBool))
{
    program->options.push_back(AnnotationArgument("persistent_heap",true));
}

if (!program->options.find("persistent_string_heap",das::Type::tBool))
{
    program->options.push_back(AnnotationArgument("persistent_string_heap",true));
}

if(!program->options.find("intern_strings",das::Type::tBool))
{
    program->options.push_back(AnnotationArgument("intern_strings",false));
}
```

**Comment by borisbat** [comment]
CodeOfPolicies has those settings explicitly. I.e. 

`
    struct CodeOfPolicies {
    // memory
        uint32_t    stack = 16*1024;                    // 0 for unique stack
        bool        intern_strings = false;             // use string interning lookup for regular string heap
        bool        persistent_heap = false;
        uint32_t    heap_size_hint = 65536;
        uint32_t    string_heap_size_hint = 65536; .....`

**Comment by borisbat** [comment]
There is version of `collect` for normal heap, which will be merged in eventually. However it is significantly more robust to use 0-GC, or, explicitly call 'delete' for large structures.

**Comment by ihm-ts** [comment]
Neat, and thanks. I tried accessing CodeOfPolicies before, but it didn't seem to affect the string heap (?), I can try it again now that the rest is working.  Great to hear it's getting merged, until then we'll use manual deallocators (or with how good our tests have gone, I might attempt to hack the string heap).

This resolves all my issues, thank you so much for the help!
