### ISSUE TITLE
Arguments' type match bug?

### ISSUE THREAD

**Issue by MaxwellGengYF** [GaijinEntertainment/daScript#1254]
Compile this code:
```
require rtti

struct MyStruct {
    value: int;
}

def my_func(t: type<auto(TT)>; func: lambda<(arg:TT?):void>) {
}

[export]
def main() {
    my_func(type<MyStruct>, @(arg: MyStruct?){

    });
}
```
got error:

error[30304]: no matching functions or generics: __::`my_func(MyStruct, lambda<(arg:MyStruct? const):void>)
test.das:13:4
    my_func(type<MyStruct>, @(arg: MyStruct?){
    ^^^^^^^
__::`my_func(MyStruct, lambda<(arg:MyStruct? const):void>)
while compiling: main: void

**Comment by borisbat** [comment]
If you need a workaround, it's 
```
def my_func(t: auto(TT); func: lambda<(arg:TT -const?):void>)
```
what happens is TT is picked up as MyStruct const, which is then applied to lambda.

In reality this generic should not match, and its currently a bug. I'll take a look shortly.

**Comment by borisbat** [comment]
https://github.com/GaijinEntertainment/daScript/pull/1255
fixed. now compiles fine
