### ISSUE TITLE
Does not compile using c++ 17 on msvc

### ISSUE THREAD

**Issue by AlvaroBarua** [GaijinEntertainment/daScript#129]
Adding this for visibility: #77 already discusses it, but seems that the fix provided at the time is no longer correct and possibly just a fluke on MSVC compiler or testing setup.

I think changes made by this issue should be reverted as that it was what I had to do to get it to compile and also @thagberg reported having to do the same to get it to compile recently.

**Comment by borisbat** [comment]
I've modified platform.h so that MSVC in any configuration uses _BitScanReverse. Trying to figure out which combination of settings enables or disalbes __builtin_clz does not seem very productive. I've tested with /std:c++17 and it now compiles and runs.

**Comment by AlvaroBarua** [comment]
Thanks!
