### ISSUE TITLE
Trying to get this to work with Delphi

### ISSUE THREAD

**Issue by jarroddavis68** [GaijinEntertainment/daScript#1317]
All the routines seems to work until I get to das_context_eval_with_catch, at which point it will crash. Any ideas about this?
```Delphi
function RunScript(const AFilename: string): Boolean;
var
  tout: Pdas_text_writer;
  dummyLibGroup: Pdas_module_group;
  fAccess: Pdas_file_access;
  ctx: Pdas_context;
  program_: Pdas_program;
  err_count: Integer;
  ei: Integer;
  error: Pdas_error;
  fnMain: Pdas_function;
  ex: PAnsiChar;
  LFilename: UTF8String;
  res: Integer;
  v: integer;
begin
  Result := False;
  LFilename := UTF8Encode(AFilename);

  das_initialize();
  try
    // Initialize resources
    tout := das_text_make_printer();
    dummyLibGroup := das_modulegroup_make();
    fAccess := das_fileaccess_make_default();
    program_ := nil;

    try
      // Get path to tutorial
      das_get_root(PUTF8Char(LFilename), Length(LFilename));

      // Compile program
      program_ := das_program_compile(AsUTF8(AFilename), fAccess, tout, dummyLibGroup);
      err_count := das_program_err_count(program_);

      if err_count <> 0 then
      begin
        // If compilation failed, report errors
        das_text_output(tout, PAnsiChar('failed to compile'#10));
        for ei := 0 to err_count - 1 do
        begin
          error := das_program_get_error(program_, ei);
          das_error_output(error, tout);
        end;
        Exit; // Early exit to perform cleanup
      end;

      // Create daScript context
      ctx := das_context_make(das_program_context_stack_size(program_));

      // Simulate the program
      res := das_program_simulate(program_, ctx, tout);
      if res = 0 then
      begin
        // If interpretation failed, report errors
        das_text_output(tout, PAnsiChar('failed to simulate'#10));
        err_count := das_program_err_count(program_);
        for ei := 0 to err_count - 1 do
        begin
          error := das_program_get_error(program_, ei);
          das_error_output(error, tout);
        end;
        Exit; // Early exit to perform cleanup
      end;

      // Find function 'main' in the context
      fnMain := das_context_find_function(ctx, PAnsiChar('main'));
      if not Assigned(fnMain) then
      begin
        das_text_output(tout, PAnsiChar('function ''main'' not found'#10));
        Exit; // Early exit to perform cleanup
      end;

      // Evaluate 'test' function in the context
      das_context_eval_with_catch(ctx, fnMain, nil);

      // Check for exceptions
      ex := das_context_get_exception(ctx);
      if ex <> nil then
      begin
        das_text_output(tout, PAnsiChar('exception: '));
        das_text_output(tout, ex);
        das_text_output(tout, PAnsiChar(#10));
        Exit; // Early exit to perform cleanup
      end;

      Result := True;
    finally
      // Cleanup resources
      if Assigned(program_) then
        das_program_release(program_);
      if Assigned(fAccess) then
        das_fileaccess_release(fAccess);
      if Assigned(dummyLibGroup) then
        das_modulegroup_release(dummyLibGroup);
      if Assigned(tout) then
        das_text_release(tout);
    end;

  finally
    das_shutdown();
  end;
end;
```

**Comment by hUwUtao** [comment]
Same issue, happen on my [project here](https://github.com/hUwUtao/dastrap/blob/5fb736469d6317df46c0b657b10e7cc21511df3a/src/interop/mod.rs#L173) which use the C api and dumped on `STATUS_ACCESS_VIOLATION`

**Comment by hUwUtao** [comment]
idk if this good, might be overflowed, as above, it throws in ucrt print?
[simulate.cpp:1740](https://github.com/GaijinEntertainment/daScript/blob/master/src/simulate/simulate.cpp#L1740)
![image](https://github.com/user-attachments/assets/21b6b9ae-173e-46cc-827b-9767d6552427)
smh.

**Comment by jarroddavis68** [comment]
Ok, so looks like no help from dev on this. I would have loved to see if I could use this in my project. Oh well. Now looking for an alternative.

**Comment by borisbat** [comment]
I'd like to help debug it remotely.
please ping me at t.me/daScript and we can coordinate

**Comment by borisbat** [comment]
> idk if this good, might be overflowed, as above, it throws in ucrt print? [simulate.cpp:1740](https://github.com/GaijinEntertainment/daScript/blob/master/src/simulate/simulate.cpp#L1740) ![image](https://private-user-images.githubusercontent.com/32933514/380502446-21b6b9ae-173e-46cc-827b-9767d6552427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDkxODQsIm5iZiI6MTczMDM0ODg4NCwicGF0aCI6Ii8zMjkzMzUxNC8zODA1MDI0NDYtMjFiNmI5YWUtMTczZS00NmNjLTgyN2ItOTc2N2Q2NTUyNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0MjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZWFjM2E0YTc2MmYyYjFmMzBlOWIyYTMxYTlkMDM4NDUwZTNiY2UzZTY3ZTE3ZGVhN2I5YzFkN2ZlNzhhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vVgkCbEyMlWcttY2jij45T0BOmnSYH6aM-8AL_JiVoI) smh.

vsnprintf 0-terminates; it also not supposed to exceed buffer size. so the only thing i can thing of, is message is somehow corrupt.

**Comment by jarroddavis68** [comment]
when I run examples from the cli, it seems to work, just running from the C api I've run into the problems. I can only run it from C api as I'm using Delphi. What I'm excited about is the fact that I dont have create wrappers for everything, can just specify the dll to use as show in the dasbind_example.

**Comment by borisbat** [comment]
So far I can only think of DAS_ENABLE_EXCEPTIONS setting. I don't know how well C++ exception model plays with Delphi or Rust for that matter, so disabling exceptions should answer that question.
Otherwise the thing to do is to have a debug build of daScript, have the integration crash, attach the debugger, and have a look.

**Comment by hUwUtao** [comment]
> > idk if this good, might be overflowed, as above, it throws in ucrt print? [simulate.cpp:1740](https://github.com/GaijinEntertainment/daScript/blob/master/src/simulate/simulate.cpp#L1740) ![image](https://private-user-images.githubusercontent.com/32933514/380502446-21b6b9ae-173e-46cc-827b-9767d6552427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDkxODQsIm5iZiI6MTczMDM0ODg4NCwicGF0aCI6Ii8zMjkzMzUxNC8zODA1MDI0NDYtMjFiNmI5YWUtMTczZS00NmNjLTgyN2ItOTc2N2Q2NTUyNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0MjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZWFjM2E0YTc2MmYyYjFmMzBlOWIyYTMxYTlkMDM4NDUwZTNiY2UzZTY3ZTE3ZGVhN2I5YzFkN2ZlNzhhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vVgkCbEyMlWcttY2jij45T0BOmnSYH6aM-8AL_JiVoI) smh.
> 
> vsnprintf 0-terminates; it also not supposed to exceed buffer size. so the only thing i can thing of, is message is somehow corrupt.

the message is not corrupt, debugger proof:
![image](https://github.com/user-attachments/assets/a77fd48e-f38b-4f5f-91d8-8fb6dd9e9f35)
further search, the das_function ptr is not nullptr but corrupted (obviously the name is weird?)
![image](https://github.com/user-attachments/assets/4da1eb5c-3860-434a-92c5-4c40d3d7c632)
im doing sanitization check on any part of my code now, perhaps das_context_eval_with_catch really broken?

**Comment by borisbat** [comment]
so, basically das_context_find_function returns garbage. In your code when program fails to compile, this happen
```
            if das_program_simulate(program, context, tout) == 0 {
                error!("VM: Simulation failed");
                let err_count = das_program_err_count(program);
                for i in 0..err_count {
                    let error = das_program_get_error(program, i);
                    if !error.is_null() {
                        das_error_output(error, tout);
                    }
                }
                das_context_release(context);
                das_text_release(tout);
                None
```
question. did program compile correctly without errors?

**Comment by hUwUtao** [comment]
> so, basically das_context_find_function returns garbage. In your code when program fails to compile, this happen
> 
> ```
>             if das_program_simulate(program, context, tout) == 0 {
>                 error!("VM: Simulation failed");
>                 let err_count = das_program_err_count(program);
>                 for i in 0..err_count {
>                     let error = das_program_get_error(program, i);
>                     if !error.is_null() {
>                         das_error_output(error, tout);
>                     }
>                 }
>                 das_context_release(context);
>                 das_text_release(tout);
>                 None
> ```
> 
> question. did program compile correctly without errors?

1. das_program_simulate is able to detect and print error
2. it finalized with a good context (no related calls raised null deref), consequence below
3. by fuzzing with `das_context_find_function` it can determine whenever a function is exported correctly or not (correctly returns a nullptr)

oh well, here is the full test result
![image](https://github.com/user-attachments/assets/7e9da819-7517-4e6c-94d5-652d57df69a7)

with the following test source (runs in wasm demo as expected)
```das
[export]
class Actor
    x: int = 0
    y: int = 1

    def inc()
    	x+=y
        y++

	def main()
    	print("Ohayo {x}\n")

[export]
def test
    print("74:cc:f0:16:d6:f6:2a:77")

[export]
def main
    var a = 1
    var b = 4
    var c = a + b
    var actorObject = new Actor()
    for i in [[int 1;2;3;4]]
        actorObject->inc()
    	actorObject->main()
    print("{c}\n")
	print("Hello World\n")

def _not_avail
    print("should not be ran")
```

**Comment by borisbat** [comment]
lets sync (via telegram or otherwise) and have a remote debugging session? i honestly can't think of why we find broken function.

**Comment by jarroddavis68** [comment]
did this ever get fixed?

**Comment by borisbat** [comment]
Nop. I've offered to do a remote debugging session - but was never
contacted. Offer stands.
https://t.me/daScript or directly.

**Comment by jarroddavis68** [comment]
Ahh, I figured it out (I think). 

its the vec4f output that is causing the issue. Delphi typically returns small records in registers by default, but vec4f must be aligned correctly and there is no built in equivalent of this. I tried to declare it like this:
```Delphi
  vec4f = packed record
    case Integer of
      0: (Data: array[0..3] of Single); // Array access for four floats
      1: (X, Y, Z, W: Single);          // Named fields for convenience
  end;
  Pvec4f = ^vec4f;

  vec4i = packed record
    case Integer of
      0: (Data: array[0..3] of Integer); // Array access for four integers
      1: (X, Y, Z, W: Integer);          // Named fields for convenience
  end;
  Pvec4i = ^vec4i;
```
To try to match the C's layout. Not sure if its correct. 

In Delphi I had to modify the signature to:
```Delphi
procedure das_context_eval_with_catch(
  context: Pdas_context;
  fun: Pdas_function;
  arguments: Pvec4f;
  out result: vec4f); cdecl;
```
I don't understand yet why you are returning this type of structure for the result. Since I do not yet understand this structure, can you offer a script example returning data so that I can validate I'm getting correct data back.

**Comment by jarroddavis68** [comment]
Yea, I can not get it return that structure properly no matter what I try. Can you explain why do you return the script return type like this? This is the problem for me. Either I need to figure how to map this delphi or create a modified version of it that can make it easier for other languages to use.

**Comment by jarroddavis68** [comment]
In the end I had to do this:
```Delphi
  {$ALIGN 16}
  __m128 = packed record
    case Integer of
      0: (m128_f32: array[0..3] of Single);
      1: (m128_u64: array[0..1] of UInt64);
      2: (m128_i8: array[0..15] of Int8);
      3: (m128_i16: array[0..7] of Int16);
      4: (m128_i32: array[0..3] of Int32);
      5: (m128_i64: array[0..1] of Int64);
      6: (m128_u8: array[0..15] of UInt8);
      7: (m128_u16: array[0..7] of UInt16);
      8: (m128_u32: array[0..3] of UInt32);
  end;

  __m128i = packed record
    case Integer of
      0: (m128i_i8: array[0..15] of Int8);
      1: (m128i_i16: array[0..7] of Int16);
      2: (m128i_i32: array[0..3] of Int32);
      3: (m128i_i64: array[0..1] of Int64);
      4: (m128i_u8: array[0..15] of UInt8);
      5: (m128i_u16: array[0..7] of UInt16);
      6: (m128i_u32: array[0..3] of UInt32);
      7: (m128i_u64: array[0..1] of UInt64);
  end;
  {$ALIGN 8} // Reset to default alignment

  vec4f = __m128;
  Pvec4f = ^vec4f;

  vec4i = __m128i;
  Pvec4i = ^vec4i;

procedure das_context_eval_with_catch_wrapper(
  context: Pdas_context;
  fun: Pdas_function;
  arguments: Pvec4f;
  result: Pvec4f
); cdecl;
 external DASCRIPT_DLL name _PU + 'das_context_eval_with_catch_wrapper';
```
Even with proper alignment, I cannot get Delphi to return a vec4f without crashing, instead I had to create a wrapper that returned a pointer to vec4f, sigh. 

Some things:
- there is not an easy, quick way to evaluate this project. You have to build the code yourself which is off putting if you're trying to see if it will work for you. I've had to learn C/C++/CMake enough to be able to do this. Lots of people simply will not, I don't think. If I were not determined to get something working because I see the potential of the product for my use case, I would have just given up and moved on. 
- The issue with working in other languages, congrats to the C interface, otherwise, dead in the water for me as I use Delphi. It just needs to be some more tweaks to make sure it is easier to work with non-C/C++ languages.

**Comment by borisbat** [comment]
@jarroddavis68 
vec4f is essentially __m128, which is SIMD register on just about any platform. For the daScript interpreter and ABI this is a native type; everything is built around it.

Are you going to submit a PR with proposed changed to C bindings, or would your like for me to do those instead?

**Comment by jarroddavis68** [comment]
> @jarroddavis68 vec4f is essentially __m128, which is SIMD register on just about any platform. For the daScript interpreter and ABI this is a native type; everything is built around it.
> 
Yea, I've come to understand about it more, working on this today.

> Are you going to submit a PR with proposed changed to C bindings, or would your like for me to do those instead?

If you can do it, it would be great. I need to recover from my deep dive into learning some C/C++/CMake and __m128 today, lol.

**Comment by jarroddavis68** [comment]
Hmm, I discovered something more, if I change the return to Pvec4 (pointer) then it does not crash and if I assigned the data to a vec4f variable, the return result seems correct.

```Delphi
function das_context_eval_with_catch(context: Pdas_context; fun: Pdas_function; arguments: Pvec4f): Pvec4f; cdecl;
  external DASCRIPT_DLL name _PU + 'das_context_eval_with_catch';
...
p := das_context_eval_with_catch(ctx, fnMain, nil)^;

```

**Comment by borisbat** [comment]
@jarroddavis68 i've added unaligned API. let me know what u think
https://github.com/GaijinEntertainment/daScript/pull/1391

**Comment by jarroddavis68** [comment]
> @jarroddavis68 i've added unaligned API. let me know what u think #1391

Ahh, wonderful, many thanks! 👍🏿

**Comment by jarroddavis68** [comment]
Ok, sweet. The `__unaligned` variants work with no issues. Again, many thanks. ❤️
