### ISSUE TITLE
Segfault on Ubuntu 18.04 'daScript telnet.das'

### ISSUE THREAD

**Issue by mingodad** [GaijinEntertainment/daScript#139]
After a release build on Ubuntu 18.04 and trying any script that uses command line parameters it segfaults:
```
daScript telnet.das 
Segmentation fault (core dumped)

```

**Comment by borisbat** [comment]
the way command line was accessed has changed since some of the samples were written. unfortunately telnet.das was one of them. i've modified the samples, as well as added command line argument validation for the 'main' functions, so that it no longer silently crashes.
