### ISSUE TITLE
double floating point postfix is different in the code and in the docs

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#161]
in the documentation double floating point literals are described with "d" postfix.  i.e. 0.0d
but in the code it causes a compilation error.
the code compiles only with "lf" posfix. i.e. 0.0lf

link to docs: daScript Reference Manual Release 0.2 beta
https://dascript.org/doc/dascript.pdf

In my opinion d postfix has better readability. 
for example 0.0lf reminds me 0.01f. also "lf" consists of 2 characters instead of one. more typing.

**Comment by AntonYudintsev** [comment]
Thanks, we will consider that
It used to be d, than change to lf, due to "%d" vs "%lf"
But your point makes sense
