### ISSUE TITLE
Is it possible to declare enums in the class scope?

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#162]
if not, what is the reason?

**Comment by AntonYudintsev** [comment]
no, it is not possible.
Why would you want to do that? How it supposed to work (besides being a namespace)?

**Comment by parallelno** [comment]
To not interfere with other enums. Exactly like enum class in c++. 
For example, we have several classes with states declared as enums. Hiding enum inside a class namespace would avoid naming collision.
