### ISSUE TITLE
how can I get a pointer of an array?

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#166]
```
[export]
def main
    var tc = new array<int>


 .code.tio:7:13:
     var tc = new array<int>             ^^^
 13:7 - 15:7

30109: can only new tuples, variants, structures or handled types, not array<int>
```

P.S. 
"Arrays can not be copied, only cloned or moved."
why does the doc say that?

**Comment by AntonYudintsev** [comment]
Doc says about variable of type "array".

Indeed, it can only be moved or cloned (obviously).
Why would you want to create a pointer on heap of array type?

**Comment by borisbat** [comment]
Array.data is already on heap. If u need variable itself you can put it in the structure.
