### ISSUE TITLE
no matching functions or generics double ( bool& )

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#167]
Please create the cast from boolean type to double. 
a workaround could be something like:
`x = b ? 1.0lf : 0.0lf`
but it is not elegant and clean as x = double(b)

**Comment by AntonYudintsev** [comment]
Hi! particular conversion from bool to any floating point can differ in different application. There is no mathematical sense in assuming that true == 1.0f (and not NAN, for example).
There is absolutely nothing that can stop you from  binding float(bool) from c++ in your own module!
It just doesn't make sense to be in in Standard Library, but you can do it for you.

or writing your own common script module with :
def to_float(a:bool)
    return a ? 1.0 : 0.
