### ISSUE TITLE
Explain shared modules in documentation

### ISSUE THREAD

**Issue by cvzakharchenko** [GaijinEntertainment/daScript#169]
"shared" is a common keyword, used when declaring a module:
`module instructions shared`
But there is no mention of it in current documentation:
https://github.com/GaijinEntertainment/daScript/blob/128cf387d0c7c6ae11447ad6034f6d74a20dcdbb/doc/source/reference/language/modules.rst

**Comment by borisbat** [comment]
I've updated documentation. It'll take a bit of time to get published on the website.

**Comment by profelis** [comment]
https://dascript.org/doc/reference/language/modules.html#shared-modules
