### ISSUE TITLE
addExtern<DAS_BIND_MEMBER_FUN example

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#171]
Hi!
Please, help me figure out the proper code for exposing a member function. I didn't find an example in your codebase.
I have a hierarchy similar below:
```
class MainClass {
    class SubClass  : public das::Module {
        FuncName(){}
        SubClass() : Module("moduleName")
            ....
            addExtern<DAS_BIND_MEMBER_FUN(FuncName)>(*this, lib, "FuncName", das::SideEffects::none, "FuncName");
            ...
    }
}
```
It spams errors. I tried to change it, but nothing helped.

**Comment by parallelno** [comment]
thank you, Boris. I changed it to
```
class MainClass {
    class SubClass  : public das::Module {
        FuncName(){}
        SubClass() : Module("moduleName")
            ....
            using method_hitMe = DAS_CALL_MEMBER(MainClass::SubClass::hitMe);
            addExtern<DAS_CALL_METHOD(method_hitMe)>(*this, lib, "hit_me", das::SideEffects::modifyArgument, DAS_CALL_MEMBER_CPP(MainClass::SubClass::hitMe));
            ...
    }
}
```
but it still gets me errors.
//
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'type': undeclared identifier	TestWorker	daScript\include\daScript\ast\ast_typedecl.h	256	
Error	C2027	use of undefined type 'das::ToBasicType<TT>'	TestWorker	daScript\include\daScript\ast\ast_typedecl.h	256	

Did I forget something? PLease, help.

**Comment by borisbat** [comment]
Likely missing type annotation for SubClass;
