### ISSUE TITLE
err = das_yyparse();        // TODO: add mutex or make thread safe?

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#181]
I run a simple example and it worked very well until it wasn't run concurrently. Then I put the code below into threads and fired them simultaneously, the program started crashing all the way.
there is the code below I borrowed from an example:
```
	NEED_ALL_DEFAULT_MODULES;
	NEED_MODULE(Module_Tutorial02);
	das::Module::Initialize();	
	// run the tutorial
	das::ModuleGroup dummyLibGroup;                      // module group for compiled program
	auto fAccess = das::make_smart<das::FsFileAccess>();      // default file access
	// compile program
	#define TUTORIAL_NAME   "test.das"
	program = compileDaScript(das::getDasRoot() + "/" + TUTORIAL_NAME, fAccess, tout, dummyLibGroup);
	...
```
Looking up the call stack I found one interesting line:
`err = das_yyparse();        // TODO: add mutex or make thread safe?`
it's from ast_parse.cpp and it's still in the recent branch.

may it be a reason for those crashes? 
Is it possible to use daScript concurrently for now?

**Comment by borisbat** [comment]
At the moment there is no way to use daScript compiler concurrently. There is long term plan to get there, but its not going to happen soon.

**Comment by parallelno** [comment]
Got it. Thanks for the reply. 
A following question. What is the best approach for compiling all the scripts in just one thread and running all of them concurrently? Is it possible?

**Comment by borisbat** [comment]
Scripts can run independently on multiple threads. You'll need unique stack per context, or at least per thread.
Compiling all the scripts on a single thread should not be an issue - compiler is ridiculously fast. We run 1800+ systems written in das, and it takes ~5 sec to compile.

**Comment by borisbat** [comment]
At some point fairly soon we'll provide serialization facilities for the 'Program'. That way precompiled scripts could be loaded with hardly any overhead. That should allow additional two orders of magnitude scaling on the volume of compiled code.

**Comment by parallelno** [comment]
For example, I need one script fired up concurrently with different input data. Should I create as many instances of a program object as threads I have or it can be just one program object with a bunch of unique contexts?

**Comment by borisbat** [comment]
Once the context is created, there is no need to keep Program around. U can create as many instances of context as you like. The easiest way to do that would be to clone the context (via copy c-tor).

**Comment by parallelno** [comment]
thanks.
I didn't get the functionality of the object: das::ModuleGroup dummyLibGroup
should it be unique per a program instance or unique per context, or not unique at all?

**Comment by borisbat** [comment]
daScript is now capable of running multiple compilation contexts (one per thread).
