### ISSUE TITLE
dasVulkan submodule commit hash is bad

### ISSUE THREAD

**Issue by zacharycarter** [GaijinEntertainment/daScript#238]
the dasVulkan submodule points to the following commit hash: https://github.com/olegus8/dasVulkan/tree/9efbb91eaa64e6f42a4ccca8e14f1ae32f2f2905 - which is no good. Breaks all recursive submodule updating / initializing.

**Comment by borisbat** [comment]
i've removed vulkan-related links until its ready for prime time again
