### ISSUE TITLE
Would you mind publishing some stable versions for some platforms?

### ISSUE THREAD

**Issue by uniqss** [GaijinEntertainment/daScript#256]
daScript is a little complex comparing with lua. So would you mind publishing some stable versions for some main platforms? It could be very helpful for us especially if we don't have some cpu or memory resources or time to compile the engine and libraries totally.

**Comment by borisbat** [comment]
https://github.com/imp5imp5/dasbox

publishes version of daScript tailored towards games as standalone applications.

**Comment by uniqss** [comment]
Thanks very much!
