### ISSUE TITLE
Some submodules require configure ssh key

### ISSUE THREAD

**Issue by spiiin** [GaijinEntertainment/daScript#266]
https://github.com/GaijinEntertainment/daScript/blob/master/.gitmodules
Не знаю, тянет ли на issue, но часть сабмодулей добавлены в формате адреса `https://github.com/borisbat/dasBGFX.git` (пуллятся через https), другие - `git@github.com:imp5imp5/dasSound.git` - через ssh. Возможно, чуть более удобнее все в одном виде перечислить

**Comment by borisbat** [comment]
and no more
