### ISSUE TITLE
Assert failed while running tutorial02_dasAot

### ISSUE THREAD

**Issue by spiiin** [GaijinEntertainment/daScript#267]
I tried to explore tutorials, I ran `generate_msvc_2019.bat` and try to compile and run tutorials projects from msvs.

I have some troubles with running `tutorial02_dasAotStub`. It return error by default, searching file `tutorial02.das` in daScript root folder (maybe it's some misconfiguration of msvs cmake). When I copy das file to root directory, script found it, but failed with assert:
```
Module `debugapi` already createdAssertion failed: 0 && "fatal error", file D:\src\daScript\src\ast\ast_module.cpp, line 177
```

I got same error both if running `tutorial02_dasAotStub` project from msvs, and also if just execute command line:
`>tutorial02_dasAot -aot tutorial2.das tutorial2.das.cpp`

Looks like it really define modules twice:
https://github.com/GaijinEntertainment/daScript/blob/master/examples/tutorial/tutorial02_dasaot.cpp#L9
And:
https://github.com/GaijinEntertainment/daScript/blob/master/utils/daScript/main.cpp#L211

Is it bug, or I did something wrong while configuring solution?

Is it possible to config aot about required modules? Also, looks like it try to require StbImage modules by default by generating file `external_need.inc` with content:
```
NEED_MODULE(Module_StbImage);
NEED_MODULE(Module_StbTrueType);
```

**Comment by borisbat** [comment]
got it fixed. was an issue of not checking module re-initialization

external_need.inc should be generated via CMAKE, with appropriate variables set to on, i.e.
        "DAS_STBIMAGE_DISABLED"     : false,
        "DAS_STBTRUETYPE_DISABLED"  : false,
