### ISSUE TITLE
Init parameters reflection

### ISSUE THREAD

**Issue by AlvaroBarua** [GaijinEntertainment/daScript#274]
Hi, I'm working getting the default initialization parameters from the scripts. 
I've managed to make it work for aliased and builtin data types, but I can't find a way of getting the value out of custom ones.

For example here: 
![image](https://user-images.githubusercontent.com/5832727/156436953-3f7bebea-ce6e-4c97-8a5b-699ba37deecf.png)
testQuat is a custom type that has an inplace constructor which generates this SimNode:
![image](https://user-images.githubusercontent.com/5832727/156438354-f00633c6-be23-4947-a756-b58a4186157c.png)
I have been looking to no avail how to properly simulate the constructor to get the data as a vec4f.

Any help will be greatly appreciated.

PD: I know I can probably alias the quaternion as a float4, but it would be good to know the proper approach as I will be adding more data types in the future. Thanks!

**Comment by borisbat** [comment]
if i understood the question correctly, easiest would be to use macros on top of ast, instead of rtti.

**Comment by AlvaroBarua** [comment]
So there is no straight forward way of doing so? 
What I'm doing at the moment is going through all structures in the module and doing reflection on the ones that satisfy a specific condition, the part that complicates thing for me is here:

![image](https://user-images.githubusercontent.com/5832727/157750508-197548d3-6355-42b5-b6b5-a46e2a162920.png)

If you could point me into some example code or provide some more insight, it would be really helpful. 
To provide some extra context, this is how I am setting up the quat class:

![image](https://user-images.githubusercontent.com/5832727/157751791-b45ee414-3169-4fc2-bfba-60d8a1facebf.png)

PS: Sorry for uploading images, but for some reason code sections are broken for me.

**Comment by borisbat** [comment]
Ok. So assuming that your init expression has no side effects, and your custom type is bound as by reference value (structure, etc).

**Comment by borisbat** [comment]
https://github.com/GaijinEntertainment/daScript/blob/master/examples/test/misc/dump_fields.das
example of the annotation, which iterates through fields, and reports names and prints initialization ast, as well as the example on how to use it 
https://github.com/GaijinEntertainment/daScript/blob/master/examples/test/misc/dump_fields_example.das

I'm going to assume that you'd like to do something more than just printing. 

https://github.com/GaijinEntertainment/daScript/blob/master/examples/test/misc/gen_fields.das
gen_fields is a little_bit more involved example. "dump" annotation generates some sort of 'registration' at script initialization time. "dump2" performs similar functionality in a tad more limited fashion, but at compilation time - and produces no initialization artifacts.
