### ISSUE TITLE
Could you please provide the information how to use dascript with 3D (opengl or BGFX). I was trying to enable in cmake option BGFX, but with this I am getting error

### ISSUE THREAD

**Issue by lvdpower** [GaijinEntertainment/daScript#322]
Could you please provide the information how to use dascript with 3D (opengl or BGFX). I was trying to enable in cmake option BGFX, but with this I am getting error - [ 27%] Built target daScript
[ 27%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/opengl_boost.das -> /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasOpenGL/opengl/_aot_generated/dasImguiOpenGL_AOT_opengl_boost.das.cpp
[ 27%] Built target dasImguiOpenGL_AOT_opengl_boost.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_demo.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_demo.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_demo.das_aot
[ 28%] AOT precompiling /Users/timur/Grafics/daScript/modules/dasImgui/example/imgui_opengl2.das -> /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
saving to /Users/timur/Grafics/daScript/modules/dasImgui/example/_aot_generated/dasImguiOpenGL_AOT_imgui_opengl2.das.cpp
[ 28%] Built target dasImguiOpenGL_AOT_imgui_opengl2.das_aot
make[2]: *** No rule to make target ../modules/dasImgui/imgui/imgui_boost.das', needed by ../modules/dasImgui/imgui/_aot_generated/dasImguiOpenGL_AOT_imgui_boost.das.cpp'. Stop.
make[1]: *** [CMakeFiles/dasImguiOpenGL_AOT_imgui_boost.das_aot.dir/all] Error 2
make: *** [all] Error 2 . I have installed BGFX library in system via build this https://github.com/bkaradzic/bgfx.cmake and sudo make install , but this did not help. I also was trying with DASBOX, but iot seems it does not provide 3d GAPI.. (only 2d may be I am wrong... I do not know) Thank you and for any who can help. [timur123@gmail.com](mailto:timur123@gmail.com) Timur

**Comment by borisbat** [comment]
Tested installer. Everything builds and runs. With BGFX. Had to fix a few things, im guessing it addressed your issue as well.
