### ISSUE TITLE
GCC / C++ 11 compatibility

### ISSUE THREAD

**Issue by rochus-keller** [GaijinEntertainment/daScript#34]
I tried to compile with GCC 4.8.2 on Ubuntu 14.4 LTS. Since you state on your website "you only need C++11 compiler" this setup should work, but it doesn't.

First of all I had to add the following to CMakeLists.txt:
set (CMAKE_CXX_STANDARD 11) 
add_compile_options(-mssse3)

Then I had to replace all make_unique and make_shared in ast.cpp and ast_module.cpp. 

Then I had to replace the variadic method template addCall in ast.h line 519 by two versions, one with one and the other with two parameters, because passing the template parameter pack to the innermost constructor (by lambda capture) doesn't seem to work in C++11.

But now I'm stuck because I get hundereds of errors in module_builtin.cpp, see 
[errors.txt](https://github.com/GaijinEntertainment/daScript/files/3512073/errors.txt)

Would be really great if I could compile it with C++11, but seems like a lot of work to make this happen; or did I miss something?

**Comment by AntonYudintsev** [comment]
Thank you. It was C++11 initially, then it became (partially) C++14, while documentation still says C++11.
We would look into possibility making it C++11 again - in the moment I have just updated documentation.

**Comment by AntonYudintsev** [comment]
And SSSE3 isn't really needed (it won't be calling SSSE3 instructions, unless compiled with it's support), it is a matter of including header.

**Comment by rochus-keller** [comment]
Ok, thanks. I thus close the issue for now since C++11 support is (unfortunately) no longer a supported feature.
