### ISSUE TITLE
Build failure, incomplete type, GCC/Clang, Ubuntu 22.04

### ISSUE THREAD

**Issue by j-martina** [GaijinEntertainment/daScript#366]
Specifically, Linux Mint 21 Vanessa, which ships libstdc++12 and libc++14.
Commit is latest master as of time of writing (72386715).
Compiler information GCC:
```
-- The C compiler identification is GNU 9.5.0
-- The CXX compiler identification is GNU 9.5.0
```
Compiler information Clang:
```
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
```
---
'src/builtin/module_builtin_network.cpp' reports that the initialization at the following line relies on an incomplete type:

```c++
static atomic<int32_t> g_moduleNetworkTotalServers{0};
```

Steps to reproduce:

1. Clone, `git submodule update --init --recursive`.
2. Modify '/generate_gcc_linux_release.sh' to include arguments setting `-DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=YES`. Run it.
3. `cd cmake_temp ; make`.

I can temporarily fix it for either compiler by putting `#include <atomic>` under `#include "module_builtin_rtti.h"`, but if it's not needed for other platforms it should probably be wrapped with `#ifdef __linux__`.

I noticed that the most recent Linux CI was run on 2022/08/30 but the atomic itself was introduced on 2022/09/08, so this may be a regression. I acknowledge that I might be missing a build configuration step. If I can help to improve existing Linux build instructions through this, let me know.

---
Addendum: Changing the required standard is necessary due to the following when `CMAKE_CXX_STANDARD` is set to 14 or earlier:

```
In file included from /home/jerome/Data/daScript/include/daScript/daScript.h:7,
                 from /home/jerome/Data/daScript/examples/profile/test_profile.cpp:5:
/home/jerome/Data/daScript/include/daScript/ast/ast_handle.h: In static member function ‘static void das::registerVectorFunctions<TT, false>::init(das::Module*, const das::ModuleLibrary&, bool, bool)’:
/home/jerome/Data/daScript/include/daScript/ast/ast_handle.h:507:23: error: ‘is_default_constructible_v’ is not a member of ‘std’; did you mean ‘is_default_constructible’?
  507 |             if ( std::is_default_constructible_v<typename TT::value_type> ) {
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       is_default_constructible
/home/jerome/Data/daScript/include/daScript/ast/ast_handle.h:507:73: error: expected ‘(’ before ‘>’ token
  507 |             if ( std::is_default_constructible_v<typename TT::value_type> ) {
      |                                                                         ^
      |                                                                         (
/home/jerome/Data/daScript/include/daScript/ast/ast_handle.h:507:75: error: expected primary-expression before ‘)’ token
  507 |             if ( std::is_default_constructible_v<typename TT::value_type> ) {
      |
```

**Comment by borisbat** [comment]
fixed
