### ISSUE TITLE
How to hot fix the aot code?

### ISSUE THREAD

**Issue by ifeuille** [GaijinEntertainment/daScript#370]
For example, modify the script of tutorial02aot:
````
require tutorial_02

def test_call
    print("this tutorial utilizes basic builin module with constant and function\n")

[export]
def test
    test_call()
    let sq2 = SQRT2
    print("sq2 = {sq2} // expecting sqrt(2), 1.41421\n")
    let xma = xmadd(sq2,sq2,1.0,1.0)    // sq2*sq2 + 1*1 => 3
    print("xma = {xma} // expecting 3\n")
````
In this case, how to hot fix the test_call function?

**Comment by borisbat** [comment]
if i understand the question correctly, after AOT is compiled, script can be modified without recompiling
that way the same executable will not pickup test_call AOT version of the function, but will run interpreted one instead

**Comment by ifeuille** [comment]
> 
You mean we need to hot fix the whole script file?

**Comment by borisbat** [comment]
pretty much. you replace script file, and only matching bits will pick up AOT. the rest stays interpreted
