### ISSUE TITLE
what is the text encoding of daScript?

### ISSUE THREAD

**Issue by zhmt** [GaijinEntertainment/daScript#396]
cpp file encoding utf8, 
So string "tutorial_text" and "aaa" are utf8 encoding.
```c++
// msvc flags in cmake
//  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /utf-8 /fp:fast /Zc:__cplusplus")
//  add_definitions(-D_WIN32_WINNT=0x0601 -DUNICODE -D_UNICODE)

#include "daScript/daScript.h"
#include <iostream>
#include <Windows.h>

using namespace das;

const char* aaa = R""""(
[export]
def Hi
    print("hi......士大夫..\n")
)"""";

const char* tutorial_text = R""""(
require aaa

[export]
def test
    try
        Hi();
    recover
        print("done");
)"""";


int main(int, char* []) {
  // request all da-script built in modules
  NEED_ALL_DEFAULT_MODULES;
  // Initialize modules
  Module::Initialize();
  // make file access, introduce string as if it was a file
  auto fAccess = make_smart<FsFileAccess>();
  TextPrinter tout;
  ModuleGroup dummyLibGroup;

  fAccess->setFileInfo("aaa.das", make_unique<TextFileInfo>(aaa, uint32_t(strlen(aaa)), false));
  fAccess->setFileInfo("dummy.das", make_unique<TextFileInfo>(tutorial_text, uint32_t(strlen(tutorial_text)), false));
  // compile script
  auto program = compileDaScript("dummy.das", fAccess, tout, dummyLibGroup);

  // create context
  Context ctx(program->getContextStackSize());
  program->simulate(ctx, tout);
  // call context function
  ctx.eval(ctx.findFunction("test"), nullptr);
  // shut-down daScript, free all memory
  Module::Shutdown();
  return 0;
}
```

Output :
```
hi......澹ぇ澶?.
```

**Comment by borisbat** [comment]
![image](https://user-images.githubusercontent.com/272689/216906455-fad65fc7-907b-4018-a2d2-45a324b9b56b.png)

so the question is what kind of IDE\editor is used? the encoding should be utf-8

**Comment by zhmt** [comment]
vs code. 
I am sure that cpp encoding  is utf-8.
If encoding is changed to GBK, every thing is ok.

If a das script is executed by daScript.exe,  it goes well too.

**Comment by zhmt** [comment]
You can copy the code above into a cpp file,  make sure that file encoding is utf-8, and compile it (with cxx flags specifying source encoding and runtime encoding utf-8. If you compile it on windows and cmake, the flag is "/utf-8" ), this error will be reproduced.

**Comment by borisbat** [comment]
Did you by any chance try const char* aaa = u8R""""( to specify utf-8 string?
On the similar note does adding /utf-8 flag actually address the issue?

**Comment by zhmt** [comment]
/utf-8 means : msvc will treat Main.cpp as a utf-8 file,  and will initialize  var "aaa " with utf-8 bytes.

**Comment by zhmt** [comment]
Here is the source code.

[Test.zip](https://github.com/GaijinEntertainment/daScript/files/10702780/Test.zip)

**Comment by zhmt** [comment]
explanation from microsoft:
https://learn.microsoft.com/en-us/cpp/build/reference/source-charset-set-source-character-set?view=msvc-170

If you want to set both the source character set and the execution character set to UTF-8, you can use the /utf-8 compiler option as a shortcut. It's equivalent to /source-charset:utf-8 /execution-charset:utf-8 on the command line. Any of these options also enables the /validate-charset option by default.

**Comment by borisbat** [comment]
https://github.com/GaijinEntertainment/daScript/commit/8129a287482b22bf1eec2538fbcaf6f3f2d9c25b
this should do it
also specifying u8 prefix for the string literal seem to do the job as well.

**Comment by zhmt** [comment]
you're right.
My fault, I forgot this: 
```c++
int main(int, char* []) {
    SetConsoleOutputCP(CP_UTF8);
}
```
It is ok now.

**Comment by borisbat** [comment]
I've added UTF-8 version of the tutorial.
![image](https://user-images.githubusercontent.com/272689/218141169-b6f7f1c3-e6c7-4c67-8b48-af8d6f13196f.png)
