### ISSUE TITLE
How to build under msvs2019

### ISSUE THREAD

**Issue by zhmt** [GaijinEntertainment/daScript#42]
I open daScript project as an cmake folder in msvs2019, but failed to build with an error:
[1/305] cmd.exe /C "cd /D E:\gitroot\g3\g3server\libezgws\daScript\src\builtin && XXD_BIN-NOTFOUND -i fio.das fio.das.inc"
  FAILED: ../../../daScript/src/builtin/fio.das.inc 
  cmd.exe /C "cd /D E:\gitroot\g3\g3server\libezgws\daScript\src\builtin && XXD_BIN-NOTFOUND -i fio.das fio.das.inc"
  'XXD_BIN-NOTFOUND' is not a command or executable program.

**Comment by zhmt** [comment]
This is my topmost cmake file:

cmake_minimum_required (VERSION 3.8)
project ("libezgws")
add_subdirectory ("libezg")
add_subdirectory ("context")
add_subdirectory ("fiber")
add_subdirectory ("coroutine")
add_subdirectory ("ezgproxy")
add_subdirectory ("daScript")

**Comment by zhmt** [comment]
What does "XXD_BIN-NOTFOUND" mean?

**Comment by AntonYudintsev** [comment]
xxd is stringifier
it used to convert builtin *.das files into something like
char array[] ={};
so it can be used inside c++ directly

**Comment by AntonYudintsev** [comment]
and it should be optional, as generated files are also commited
(see https://github.com/GaijinEntertainment/daScript/blob/master/src/builtin/builtin.das.inc)
so you can skip it altogether

**Comment by zhmt** [comment]
It was built successfully  after all XXD command are commented .
Thanks for your help!

**Comment by zhmt** [comment]
I can start my daScript journey now.
