### ISSUE TITLE
Can you post an article about memory management in daScript

### ISSUE THREAD

**Issue by zhmt** [GaijinEntertainment/daScript#43]
I think daScript is a great script language with modern features ,  and it works seamlessly with c++, I am trying to adopt it in my game.

But I have some questions 。Words about memory management in daScript document just one line:
semi-manual memory management:

Can you explain more, or give some rules? 
Thank you.

**Comment by AntonYudintsev** [comment]
That is totally correct comment, documentation is way beyond required.
Basically, there are two ways to work with memory management from c++ side, and two - from script side.
What we normally do from C++ side, is just call 
      context.restart();
      context.restartHeaps();
on each "first run" (first in terms of call nesting, i.e. we are not calling it when script->c++->script).
That call will free all memory, and these calls are extremely cheap. With that no GC is needed at all.
The only thing required - is that there is no any global variables in script pointing to the heap (or better - no global variables at all).

The other possible way - is collect garbage (again, only from c++ side, i.e. explicit call is required). With that you can have global variables in script.

From inside script, there is option to call not only 'new', but also 'delete' (see tree benchmark).
That is unsafe, and so will require [unsafe] annotation.

We will try to make some documentation on that topic.

**Comment by zhmt** [comment]
I prefer the the way “context.restart()” , it keep things simpler.
Thank you for your explanation!

**Comment by AntonYudintsev** [comment]
Just don't forget restartHeaps() as well :)

**Comment by zhmt** [comment]
Thanks for tips that will save me from bugs, I really thought a  single "restart()" will work, I know the right way is calling them both:
context.restart();
context.restartHeaps();
