### ISSUE TITLE
why not make the syntax more pythonic?

### ISSUE THREAD

**Issue by yunfan** [GaijinEntertainment/daScript#44]
hi ,i just saw this new language, the cpp mentioned made me want to go away, then i found the code sample which just attract me at once. 

i was thinking since its just the begining, if that's not require much change, why not just use the python syntax, like `require` => `import`, this will help much more pythoner to use this language, and as i knew, there were many go user who turned from python complains the syntax

**Comment by AntonYudintsev** [comment]
technically, import in Python is different.
daScript only allows "importing" module as is, and can not "import from" (i.e. "from XXX import YYY"). 

May be still make sense to rename to "import", since language is not really Python in many other ways.
