### ISSUE TITLE
Error building daScript on CentOS

### ISSUE THREAD

**Issue by bistace** [GaijinEntertainment/daScript#45]
Hi,
I wanted to give daScript a try and was attempting to compile it on CentOS with gcc 7.3.0 but got the following error:
```
[ 26%] Built target libDaScriptJson
Scanning dependencies of target jsonTest
[ 26%] Building CXX object CMakeFiles/jsonTest.dir/examples/json/main.cpp.o
/env/ig/soft/ig/gcc-7.3.0/el6-x86_64-generic/bin/ld: liblibDaScript.a(performance_time.cpp.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/env/ig/soft/ig/gcc-7.3.0/el6-x86_64-generic/bin/ld: /lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [curlTest] Erreur 1
make[1]: *** [CMakeFiles/curlTest.dir/all] Erreur 2
make[1]: *** Attente des tâches non terminées....
[ 26%] Linking CXX static library liblibDaScriptProfile.a
[ 26%] Built target libDaScriptProfile
[ 27%] Linking CXX static library liblibDaScriptTest.a
[ 27%] Built target libDaScriptTest
[ 28%] Linking CXX executable jsonTest
/env/ig/soft/ig/gcc-7.3.0/el6-x86_64-generic/bin/ld: liblibDaScript.a(performance_time.cpp.o): in function `ref_time_ticks':
performance_time.cpp:(.text+0x15): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [jsonTest] Erreur 1
make[1]: *** [CMakeFiles/jsonTest.dir/all] Erreur 2
make: *** [all] Erreur 2
srun: error: etna59: task 0: Exited with exit code 2
```

Do you think the error comes from my side or would that be something you can fix?

**Comment by rversteegen** [comment]
You're using CentOS EL6?
https://github.com/libfuse/libfuse/issues/207

Note the message
`/lib64/librt.so.1: error adding symbols: DSO missing from command line`
This is a hint that the missing symbol is available in /lib64/librt.so.1, but -lrt wasn't passed to the linker.
-lrt is only necessary for glibc before 2.17 and older (released 2012-12-25).

**Comment by bistace** [comment]
Hi,

thanks to your help, I was able to compile daScript by adding "-lrt" to the linker options. 

Your are correct that I tried to build it on CentOS EL6. I am on a computing cluster and we are currently migrating to EL7 so I shouldn't have this problem in the future.
