### ISSUE TITLE
How can I use daScript with Godot?

### ISSUE THREAD

**Issue by Atem1995** [GaijinEntertainment/daScript#491]
How can I use daScript with Godot?
I want to try it.

**Comment by borisbat** [comment]
Keep us posted :)

**Comment by Atem1995** [comment]
Do you have any ideas?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaijinEntertainment/daScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月30日(星期天) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GaijinEntertainment/daScript] How can I use daScript with Godot? (Issue #491)





 
Keep us posted :)

**Comment by GrauBlitz** [comment]
> Do you have any ideas?

You just could create a Godot Extension and link this library to it and implement the functions which create, call and destroy everything scripting related. If you are speaking about using it like GDScript or C#: Good luck, even the C# integration took skilled devs a big chunk of time.
Sorry, but asking this questions, it looks like this is a bit ahead of your path as a programmer, keep on learning :-)
