### ISSUE TITLE
Performance comparison with Cyber

### ISSUE THREAD

**Issue by paulocoghi** [GaijinEntertainment/daScript#634]
Doing a research on new/modern scripting languages, both daScript and [Cyber](https://github.com/fubark/cyber) caught my attention, the later being based on Zig.

Would be nice to see how they compare to each other.

Thanks!

**Comment by AntonYudintsev** [comment]
Right now it seems impossible to compare anything usefull - there are almost no implemented benchmarks (besides ranged for and recursive fibonacci).
Judging by these two - it should not outperform dascript in interpretation (recursive fibonacci are almost twice faster in dascript), however, it is hardly an illustrative benchmark.
Most importantly, cyber requires JIT for FFI, which make it unacceptable for gaming consoles/iOS, and integrating with C++ is not going to be easy as well.
Comparing AoT performance (which is typical way of executing most of scripts in production environment) seem to be unfair game.
If you would able to port any reasonably representative benchmark (such as SHA/n-bodies/tree/ etc) - let us know comparison!
