### ISSUE TITLE
Missing simple example

### ISSUE THREAD

**Issue by Arcnor** [GaijinEntertainment/daScript#66]
Hello,

I've found that many interesting complex projects (like daScript) normally lack a very simple example to get started, so I hope that can be remedied :smiley:. The closest I've found is the code inside `examples/test` but that's far from simple.

It will be really helpful if an example with *only* setting up the VM context, running a simple embedded script with `print("hello world")` or equivalent, then proceeding to shutdown the library is added to either the docs or this repo.

Thanks and keep up the good work!

**Comment by AntonYudintsev** [comment]
Have you looked into:
https://github.com/GaijinEntertainment/daScript/blob/master/utils/daScript/main.cpp
It is may be a bit longer then just "run one script" as it runs as many files at once as you pass in command line, but overall still rather simple.

**Comment by Arcnor** [comment]
Right, that seems useful, although my messages was a more general example as something that can be improved. Maybe just adding that to the docs will be helpful? It might not be obvious right now.

**Comment by AntonYudintsev** [comment]
In the moment, documentation on the embedding itself is more like "absent" than "sparse"... Current documentation is about the language mostly.

I agree that it is needed, but it seems it will take a while to make it.

**Comment by AntonYudintsev** [comment]
a lot of documentation was added

**Comment by TwoDimensionsReturn** [comment]
Hello @AntonYudintsev ,

I'm trying daScript for the first time.

I'm looking for an example how to define a class in daScript (found how to) and how to instantiate it in C++. 
For this latest point, I'm a bit clueless reading the documentation and checking the examples.

My full use case will be to define a class in c++, derived from it in .das with an overridden method, then call this method in C++.
Do you any advice or example for me, please?

**Comment by AntonYudintsev** [comment]
I will start from your last (final) task.
Yes, my be certain simple sample would be worth making.
But as for now, you can look into DebugAgentAdapter or DataWalkerAdapter. That is doing exactly what you want.
sample is coming

**Comment by TwoDimensionsReturn** [comment]
thanks a lot, I'll have a shot
