### ISSUE TITLE
Array initialization issues

### ISSUE THREAD

**Issue by stefandd** [GaijinEntertainment/daScript#67]
1. The documentation (https://dascript.org/doc/reference/language/expressions.html?highlight=initalization) in 2.4.4. gives a `,` syntax for array initalization (leading to a syntax error) but 2.6 uses `;`. Therefore `d = [[int[] 1, 2]]     // creates array of two elements` as provided as example in 2.4 does not work

2. Could you please provide an example for a multidimensional array initialization? (no example can be found in the documentation). The following do not work.
`var arr : float[2][2] = [[ float[2] [1.; 2.]; [3.; 4.] ]] // does not work`
`var arr : float[2][2] = [[ float [1.; 2.]; [3.; 4.] ]] // doesn't work either`

**Comment by borisbat** [comment]
Only dynamic multi-dimensional arrays can be initialized (for now)::

    var a <- [[auto [{int 1;2;3}]; [{int 4;5}]]]    // array<int>[2]
    var a <- [{auto [{int 1;2;3}]; [{int 4;5}]}]    // array<array<int>>
