### ISSUE TITLE
Wrong string representation/print for fixed size arrays

### ISSUE THREAD

**Issue by stefandd** [GaijinEntertainment/daScript#68]
The following code
```
let
    N = 2

var 
    a : float[N][N]

[export]
def main
    print("{a}\n")
    return true
```
should print:
`[[ [[ 0; 0]]; [[ 0; 0]] ]]`

but instead prints twice as many elements:
`[[ [[ 0; 0]]; [[ 0; 0]]; [[ 0; 0]]; [[ 0; 2.10195e-44]]]]`

This is a problem for debugging that relies a lot on print()

**Comment by borisbat** [comment]
Fixed in the latest master. Additionally there were numerous bugs in multi-dimensional array handling, which are now fixed as well.

also, debug(a) produces more detailed output, than print. sprint version is also available. on that same note stackwalk() helps debugging
