### ISSUE TITLE
Why so big executable daScript 60MB ?

### ISSUE THREAD

**Issue by mingodad** [GaijinEntertainment/daScript#74]
Hello !
Interesting project !
When I compile through "generate_gcc_release.sh" and striping "bin/daScript" it ends up with 60MB:
```
-rwxrwxr-x 1 xxxx xxxx 62013056 sep 22 11:20 daScript
```
It's a strange big executable size for a scripting language, what's the rationale for that ?

Cheers !

**Comment by AntonYudintsev** [comment]
Interesting, will take a look there.
On clang/windows it is 10 times smaller.

**Comment by AntonYudintsev** [comment]
Thank you for that Issue.
We have already found several configuration settings that result in both executable size and performance degradations (such as asserts left in release build!).
We have managed to decrease size to 34mb, just by that
It is also possible to further significantly decrease size
if in CMakeCommon.txt find
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -fno-rtti -fno-exceptions -fomit-frame-pointer -fno-stack-protector -s -DDAS_FUSION=1")
you replace -O3 with -Os size drops to 23mb (~-30%) and difference in performance _in interpretation_ is almost zero (of course, c++ or AOT code performance can and will change, especially in loops). It is possible to generate code with different settings for interpretation and AOT files, but we leave this to application integration.


Even further, if you replace -DDAS_FUSION=1 with -DDAS_FUSION=0 size becames 12mb (yet another 50%), with a cost of switching off fusion engine. Which wont affect performance of AOT, but can affect interpretation performance. We have not investigate performance impact, and it can vary from test to test.

The total size is still 12MB, which is more than twice higher than size of executable binaries in Windows, so may be it worth looking into even further, but as for today I think it is kinda enough :)

Additionally, if you enable LTO you can shave off couple of megabytes and get some performance, but link time will become insanely high on gcc.

Hope that settles the issue

**Comment by onehundredfeet** [comment]
lib
My Experiments on Mac OSX 10.15, Xcode 12
Default Release size: 36.7M
Dead Code Stripping: 35..9M
Change to "-Os" : 32.6 
-DDAS_FUSION=0 : 18.8 (I have serious concerns about using this option)
running `strip daScript` 11.5M. (Tons of symbol data not stripped during link)

For comparison. all of SDL is 1.5M. I don't really understand why the compiler is inflating the size so far.

**Comment by AntonYudintsev** [comment]
With recent optimizations and compiler fixes, the size of code has been reduced 2-4 times (that also resulted in compile time reduction). Further optimizations are possible, but provides diminishing returns.
So, I am closing the issue, thank you for your feedback.

**Comment by onehundredfeet** [comment]
Wow Anton! Thanks! Great work!
