### ISSUE TITLE
Mac build doesn't seem to work.

### ISSUE THREAD

**Issue by onehundredfeet** [GaijinEntertainment/daScript#76]
The last OS mentioned was 10.12 in the generate_xcode. I'm on 10.15. 

Do I need a particular version of Xcode to make the build? I'm getting errors on the __func__ usage, which is a reserved word. It shouldn't be used as a variable.

<snip>

In file included from daScript/src/builtin/module_builtin_debugger.cpp:43:
daScript/src/builtin/debugapi_gen.inc:151:81: error: expected ')'
  static __forceinline bool invoke_canVisitHandle ( Context * __context__, Func __func__, void * self, void * const  ps, TypeInfo const  & ti ) {
                                                                                ^
daScript/src/builtin/debugapi_gen.inc:151:51: note: to match this '('
  static __forceinline bool invoke_canVisitHandle ( Context * __context__, Func __func__, void * self, void * const  ps, TypeInfo const  & ti ) {
                                                  ^
daScript/src/builtin/debugapi_gen.inc:160:84: error: expected ')'
  static __forceinline bool invoke_canVisitStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                                                   ^
daScript/src/builtin/debugapi_gen.inc:160:54: note: to match this '('
  static __forceinline bool invoke_canVisitStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                     ^
daScript/src/builtin/debugapi_gen.inc:169:82: error: expected ')'
  static __forceinline void invoke_beforeStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                                                 ^
daScript/src/builtin/debugapi_gen.inc:169:52: note: to match this '('
  static __forceinline void invoke_beforeStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                   ^
daScript/src/builtin/debugapi_gen.inc:178:81: error: expected ')'
  static __forceinline void invoke_afterStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                                                ^
daScript/src/builtin/debugapi_gen.inc:178:51: note: to match this '('
  static __forceinline void invoke_afterStructure ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {
                                                  ^
daScript/src/builtin/debugapi_gen.inc:187:87: error: expected ')'
  static __forceinline void invoke_afterStructureCancel ( Context * __context__, Func __func__, void * self, void * const  ps, StructInfo const  & si ) {Func

**Comment by onehundredfeet** [comment]
I'm also getting issues with the struct keyword in the .inc 

 static __forceinline void invoke_beforeArray ( Context * __context__, Func func, void * self, **struct** debugapi::DapiArray const  & pa, TypeInfo const  & ti ) {
    das_invoke_function<void>::invoke
      <void *,struct debugapi::DapiArray const  &,TypeInfo const  &>
        (__context__,func,
          self,pa,ti);
  }

**Comment by onehundredfeet** [comment]
After modifying the files manually, it all compiles, so I think it's just a bad variable name and the extra struct.

Also, the lib size seems enormous.

Debug - 400+MB
Release - 57MB

Is that expected?

![Screen Shot 2020-10-03 at 6 35 10 PM](https://user-images.githubusercontent.com/4307661/95004976-4594f780-05a7-11eb-8359-b87671400512.png)
![Screen Shot 2020-10-03 at 6 35 01 PM](https://user-images.githubusercontent.com/4307661/95004977-4af24200-05a7-11eb-9aa5-b699c1bb5e81.png)

**Comment by onehundredfeet** [comment]
The .o files add up correctly. There's some pretty large .o files given the source size:

![Screen Shot 2020-10-03 at 7 02 23 PM](https://user-images.githubusercontent.com/4307661/95005274-17191b80-05ab-11eb-847b-6cf56a9d7588.png)

**Comment by onehundredfeet** [comment]
Full command line for the ast_simulate.o

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target x86_64-apple-macos10.12 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++1z -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Release\" -DITS_PLATFORM_APPLE=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -IdaScript/cmake_temp/Release/include -IdaScript/include -IdaScript/cmake_temp/DAS.build/Release/libDaScript.build/DerivedSources-normal/x86_64 -IdaScript/cmake_temp/DAS.build/Release/libDaScript.build/DerivedSources/x86_64 -IdaScript/cmake_temp/DAS.build/Release/libDaScript.build/DerivedSources -FdaScript/cmake_temp/Release -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -Wno-register -fno-rtti -fno-exceptions -fomit-frame-pointer -fno-stack-protector -DDAS_FUSION=1 -DNDEBUG=1 -Wall -Wextra -pedantic -MMD -MT dependencies -MF daScript/cmake_temp/DAS.build/Release/libDaScript.build/Objects-normal/x86_64/ast_simulate.d --serialize-diagnostics daScript/cmake_temp/DAS.build/Release/libDaScript.build/Objects-normal/x86_64/ast_simulate.dia -c daScript/src/ast/ast_simulate.cpp -o daScript/cmake_temp/DAS.build/Release/libDaScript.build/Objects-normal/x86_64/ast_simulate.o

**Comment by borisbat** [comment]
1. fixed the mac build. were some work-in-progress issues with class adapter generators (they streamline C++ class binding)
2. turned off fusion by default in debug. that cuts down to 284 mb
3. to trim the size significantly in release DAS_FUSION should be set to 0, and optimizations changed to 'size' from 'speed'. that puts libDaScript.a down to 30mb in release, and daScript.exe down to 18mb. there are some performance implications for the interpreter, but it hardly affects AOT code.
4. libraries largely consist of debug info, especially in 'debug' builds. daScript generates a lot of classes

overall will be looking into shrinking the size of the binaries in the near future

**Comment by AntonYudintsev** [comment]
Initital issue (mac build) is fixed, the other (size) is duplicate
