### ISSUE TITLE
Feature Request - String Script Compile

### ISSUE THREAD

**Issue by onehundredfeet** [GaijinEntertainment/daScript#78]
A lot of games use some kind of file packing system. Would be great to be able to send a string instead of a file to be compiled by 'compileDaScript'.

**Comment by AntonYudintsev** [comment]
Gaijin is not an exception, and we definetly use file packing system. There is even DAS_NO_FILEIO define, which switches of default file access (as some game platforms won't allow it anyway)

To make support of any file pcking system can just implement:
class MyFileAccess final : public das::ModuleFileAccess{};
override those two functions  (getNewFileInfo and getModuleInfo) and pass that to compileDaScript
In addition to that  you can override class MyFileInfo final : public das::FileInfo {}, if, for example, you have some kind of memory mapped files.

Default implementation is include\daScript\simulate\fs_file_info.h but noone is required to use default.

Allowing send "just string" isn't really an option for more or less sophisiticated project, as most of scripts will require other some other modules anyway.

**Comment by borisbat** [comment]
[code]
        auto access = make_smart<FileAccess>();
        auto fileInfo = make_unique<FileInfo>((char *) str, uint32_t(str_len));
        access->setFileInfo(modName, move(fileInfo));
[/code]

is the simplest way to introduce string to file access as if it was a file.

**Comment by AntonYudintsev** [comment]
https://github.com/GaijinEntertainment/daScript/blob/master/examples/tutorial/tutorial00.cpp
