### ISSUE TITLE
Missing check in AOT for conflicting enum names

### ISSUE THREAD

**Issue by emelrad12** [GaijinEntertainment/daScript#79]
In path tracer example change no_aot to false, generated code wont work because there are 2 enums called type, one from dascript and one from debug_info.h

Workaround: change all occurrences of type in dascript to typer(or anything)

It would be nice to scramble the enum names from dascript.

**Comment by borisbat** [comment]
I've pushed different workaround; specifying module provides a namespace.
At this point assigning automatic namespace seems like the most reasonable solution moving forward; I need to think of the scheme of automatically generating them. Alternatively dasAot can report errors when namespace is not specified.
