### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by sirinath** [GaijinEntertainment/daScript#834]
The current array syntax can be improved. 

We can just use `array`

E.g.

```
a: array<ElementType, IndexType>(Dimension1, Dimension2, ...)[IndexRange1, IndexRange2, ....]
```

**Comment by borisbat** [comment]
dynamic arrays are single-dimenstion and resizeable. static array covers case with fixed dimensions, i.e. a : ElementType[IndexRange1][IndexRange2...]. At some point IndexType will be extended to 64-bit integers, in the meantime signed and unsigned 32 bit integers are it.
