### ISSUE TITLE
Returning multiple items from c++ function to dascript

### ISSUE THREAD

**Issue by devilinthedata** [GaijinEntertainment/daScript#87]
Is dascript able to return multiple variables from a c++ function, back into script? Something along the lines of:

[length,colour,angle] = docalc()

Where docalc() is a c++ function registered to be callable from dascript

Thanks for your help

Matt

**Comment by AntonYudintsev** [comment]
No, unfortunately I can't see easy way to do it.
Obviously, you can call a function with mutable var references as out parameters.

**Comment by devilinthedata** [comment]
Thanks for your reply Anton. Will use another method, as you say.
