### ISSUE TITLE
var declaration outside of function

### ISSUE THREAD

**Issue by taylorius** [GaijinEntertainment/daScript#92]
Why do vars, when declared outside of a function, need a carriage return, so the variable is on the line below the "var" statement? This keeps tripping me up, and personally I wish it were not the case. :-) 

e.g. from the pathtracer example

var
    RAND_SEED : int4

Whereas within a function, one can write    var a:int    without any problems.

**Comment by borisbat** [comment]
i've added support for a single-line global variables
multile global variables can still be declared in a block
i.e

**Comment by AntonYudintsev** [comment]
Primarily it is because we (internally) prefer to avoid global variables, and when we need them, we usually need more than one, so blocked syntax was sufficient, i.e.
```
let
    x = 10
    y = 11

**Comment by devilinthedata** [comment]
Hey, thanks so much for that! I just tried it with the latest version, and it works a treat! Awesome.

**Comment by taylorius** [comment]
Hey, thanks so much for that! I just tried it with the latest version, and it works a treat! Awesome.
