### ISSUE TITLE
Is it possible to define a single module across multiple files?

### ISSUE THREAD

**Issue by jemoo** [GaijinEntertainment/daScript#993]
mainly to solve the issue of mutual type references within a single module, without having to put all types in a single file.
thanks!

**Comment by borisbat** [comment]
there is 'include' directive, similar to 'require'
otherwise we are looking into possible solutions, but general idea was acyclic module graph :|

**Comment by jemoo** [comment]
I tried the "include" directive, and it solved my problem very well. Thank you.
